default: &default
  # Database configuration
  DB_PORT: "5432"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  DB_DATABASE: "database name"
  DB_USERNAME: "database username"
  DB_PASSWORD: "database password"
  # Mailer configuration
  MAILER_SMTP_ADDRESS: "smtp email address"
  MAILER_SMTP_DOMAIN: "smtp email domain"
  MAILER_SMTP_PORT: "587"
  MAILER_SMTP_USER_NAME: "smtp email username"
  MAILER_SMTP_PASSWORD: "smtp email password"
  # GeoCoder configuration (developer.here.com)
  GEOCODER_LOOKUP_API_KEY: "here_api_key"
  SECRET_KEY_BASE: "secret_key_base"

development:
  <<: *default

integration:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

staging:
  <<: *default

production:
  <<: *default
